export const GET_API_USERS_REQUEST_FOR_MY_TASK = 'GET_API_USERS_REQUEST_FOR_MY_TASK';
export const GET_API_USERS_SUCCESS_FOR_MY_TASK = 'GET_API_USERS_SUCCESS_FOR_MY_TASK';
export const GET_API_USERS_FAIL_FOR_MY_TASK = 'GET_API_USERS_FAIL_FOR_MY_TASK';